### PR TITLE
switch to jcenter as the maven repository, and remove java CLI scripts

### PR DESCRIPTION
**Pull request by dtanner**
Since this is an open source project, I created a Gravie organization at jcenter, and put this repo under that org.
Here's the jcenter URL for the repo: https://bintray.com/gravie/maven/aws-crypto-tools-java/view

This change moves the publishing location to that new repo.  Also removed the groovy CLI scripts, since AFAIK everyone should use the Go CLI scripts from now on.

### CODE REVIEW

**Comment by gharcombe-minson** [comment]
:+1:

**Comment by lanejo01** [comment]
:+1:

**Comment by dtanner** [comment]
@gharcombe-minson - can you merge this when you get a chance?  No hurry, but looks like I only have read access to the repo right now.  Thanks.

**Comment by lanejo01** [comment]
Dan you should totally demo this. Missed you at the groovy meetup in town!

**Comment by mbrose** [comment]
@dtanner you should have write access now. Sorry about that.

**Comment by dtanner** [comment]
woohoo!  now rip it all out and use the amazon SDK ;-)

**Pull request merged**
